baseURL = 'https://cjazzuk.github.io/cjazz/'
languageCode = 'en-gb'
title = 'cjazz'
theme = "bridget"
# publish the built site into/docs so GitHub Pages can serve it
publishDir = "docs"

# Optional but helpful on GitHub Pages if you see broken paths:
# relativeURLs = true
# canonifyURLs = true
[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Photos"
    url = "/photos/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
